[MEDIA]
RECORD_WAV_ROOT=D:\AI114\media\record
TTS_WAV_ROOT=D:\\AI114\media\tts\
SWZC_WAV_ROOT=D:\\AI114\media\swzc

[MSG]
MSG_SERVER_ADDR=192.168.10.2
MSG_SERVER_PORT=5672
MSG_SERVER_USER=admin
MSG_SERVER_PASSWORD=admin

#MSG.py IP Address
MSG_VOICECARD_PROXY_ADDR=192.168.10.176

#AI114.exe IP Address
VOICECARD_APP_ADDR=192.168.10.176

[DB]
DB_SERVER_ADDR=127.0.0.1
DB_SERVER_PORT=3306
DB_SERVER_DATABASE=rgt
DB_SERVER_USER=root
DB_SERVER_PASSWORD=mysql

[System]
EARLY_RECORD_TIME=0.5
ENABLE_PLAY_INTERRUPT=0
#指定SOCKET地址，将是被结果发送过去
SOCKETIP1=http://192.168.10.201:20000
SOCKETIP2=http://192.168.10.202:20000
[Channel]
Start=0

[VOICEPRINT]
VP_SERVER_URL=http://192.168.10.176:5004
VP_SERVER_HOST=0.0.0.0
VP_SERVER_PORT=5004
# VP_SERVER_MEDIA_PATH=D:\AI114\media\voiceprint\
VP_SERVER_MEDIA_PATH=D:\AI114\media\record\
JXT_SPEAKER_ID_SERVICE_PORT=9001

[DIALOUT]
AUDIO_ROOT=Y:\xjzhkfcode\server\~\data\InfoPlatform\aifile
RECORD_ROOT=Y:\xjzhkfcode\server\~\data\InfoPlatform\aifile\DIALOUT\RECORD\
Node_UDP_IP = 192.168.10.221
Node_UDP_PORT = 41235
DailOut_UDP_IP = 192.168.10.176
DailOut_UDP_PORT = 41234
AUDIO_ROOT_NODE=D:\xjzhkfcode\server\~\data\InfoPlatform\aifile\DIALOUT\RECORD\
AUDIO_TO_TXT = 5002
